- name: Demo on condition
  hosts: localhost
  tasks:
    - name: say Hi to ram
      ansible.builtin.debug:
        msg: Hey,John
        when: user == "ram"

    - name: say Hi to john
      ansible.builtin.debug:
        msg: Hey,John
        when: user == "john"

