- name: filter
  hosts: localhost
  vars:
    URL: https://nginx.org/download/nginx-1.25.3.zip
  tasks:
    - name: Filter
      ansible.builtin.unarchive:
        src: "{{ URL }}"
        dest: /tmp
        remote_src: yes

    - name: URL split
      ansible.builtin.debug:
        msg: "{{ URL | split('/') | last | regex_replace('') }}"

 # last | regex_replace('') }}" ---- used for only displaying  last word of url which is defined that is :nginx-1.25.3.zip