- name: Ignore demo
  hosts: localhost
  tasks:
    - name: Run shell command
      ansible.builtin.shell: exit 1
      ignore_errors: yes

    - name: say hi
      ansible.builtin.debug:
        msg: hi