- name: loops
  hosts: localhost
  tasks:
    - name: loop demo
      ansible.builtin.debug:
        msg: hello , "{{ item }}"
      loop:
        - ram
        - sita
        - laxman

    - name: loop demo on maps
      ansible.builtin.debug:
        msg: hello, "{{ item.name }}", Age of yours "{{ item.age }}" years.
      loop:
        - { name: "ram", age: 20 }
        - { name: "rahim", age: 30 }
        - { name: "abdul", age: 40 }
